### PR TITLE
Use actual literal name of injected dependency

### PR DESCRIPTION
**Pull request by mihneasim**
Otherwise these will be false negatives:
```javascript
angular.module(app).service('GoodService', ['MyHttp', function($http) {
  this.fetch = function() {
    return $http.get('/items')
  }
}])
```

### CODE REVIEW

**Comment by tregusti** [comment]
Thank you for this PR, but as you can see, the tests fail. Please do fix and add those and I will happily merge it.

**Comment by mihneasim** [comment]
Oops, this was embarrassing, i didn't check for tests.
Fixed and covered the use case, ready for review, thank you @tregusti !

**Comment by tregusti** [comment]
I'm sorry for the delay. Thank you!

I squashed the commits though.

**Comment by mihneasim** [comment]
@tregusti makes sense, thank you for the quick release!

**Pull request closed without merging**
